#!/usr/bin/env python3
"""
Printed Dipole Antenna with Microstrip Balun Design
Using PyAEDT HFSS

Center Frequency: 2.217 GHz
Substrate: FR4 (εr = 4.4)
"""

import numpy as np
import os
import sys

# ============================================================================
# STEP 1: Design Parameters
# ============================================================================
print("=" * 70)
print("STEP 1: Design Parameters")
print("=" * 70)

# Physical constants
c = 3e8  # Speed of light (m/s)
epsilon_r = 4.4  # FR4 relative permittivity

# Frequency parameters
f_center = 2.217e9  # Center frequency (Hz)
f_min = 1.5e9  # Sweep start (Hz)
f_max = 3.0e9  # Sweep end (Hz)
f_step = 0.01e9  # Sweep step (Hz) - 0.01 GHz

# Wavelength calculations
lambda_0 = c / f_center  # Free space wavelength
lambda_g = lambda_0 / np.sqrt(epsilon_r)  # Guide wavelength in FR4

# Dipole parameters
L_dipole_initial = 50e-3  # Initial dipole arm length (m) - 50mm
W_dipole = 3e-3  # Dipole arm width (m)

# Balun parameters (microstrip tapered balun)
L_balun = lambda_g / 4  # Balun length (quarter wavelength)
W_feed_start = 1e-3  # Balun narrow end width (m)
W_feed_end = 3e-3  # Balun wide end width (m) - matches dipole width

# Substrate parameters
L_substrate = 120e-3  # Substrate length (m)
W_substrate = 60e-3  # Substrate width (m)
H_substrate = 1.6e-3  # Substrate thickness (m) - typical FR4

# Ground plane
L_gnd = L_substrate
W_gnd = W_substrate

print(f"Center Frequency: {f_center/1e9:.3f} GHz")
print(f"Free Space Wavelength (λ0): {lambda_0*1e3:.2f} mm")
print(f"Guide Wavelength (λg) in FR4: {lambda_g*1e3:.2f} mm")
print(f"Initial Dipole Arm Length: {L_dipole_initial*1e3:.1f} mm")
print(f"Balun Length (λg/4): {L_balun*1e3:.2f} mm")
print(f"Substrate Size: {L_substrate*1e3:.1f} x {W_substrate*1e3:.1f} x {H_substrate*1e3:.2f} mm")
print()

# ============================================================================
# STEP 2: Calculate Optimal Dipole Length
# ============================================================================
print("=" * 70)
print("STEP 2: Calculate Optimal Dipole Length")
print("=" * 70)

# For a half-wave dipole, the physical length is approximately λg/2
# accounting for end effect (typically 0.5-5% shorter)
L_dipole_optimal = lambda_g / 2 * 0.95  # End effect correction factor

print(f"Optimal Half-Wave Dipole Length (with end effect): {L_dipole_optimal*1e3:.2f} mm")
print(f"Initial length for parameter sweep: {L_dipole_initial*1e3:.1f} mm")
print()

# ============================================================================
# STEP 3: Create HFSS Script
# ============================================================================
print("=" * 70)
print("STEP 3: Generate HFSS Python Script")
print("=" * 70)

# Generate the complete PyAEDT script
hfss_script = '''
"""
Printed Dipole Antenna with Microstrip Balun - HFSS Simulation
Generated by cli-anything-pyaedt

Antenna Specifications:
- Type: Printed Dipole with Microstrip Balun
- Center Frequency: {f_center:.3f} GHz
- Substrate: FR4 (εr = {epsilon_r})
- Initial Dipole Length: {l_dipole:.1f} mm
"""

import numpy as np
import time

# Patch DesignSettings for AEDT 2019 compatibility
try:
    import pyaedt.application.Design as dm
    _orig_init = dm.DesignSettings.__init__
    def _patched_init(self, app):
        try:
            _orig_init(self, app)
        except AttributeError:
            self._app = app
            self.design_settings = None
            self.manipulate_inputs = None
    dm.DesignSettings.__init__ = _patched_init
except Exception:
    pass

from pyaedt import Hfss

# ============================================================================
# DESIGN PARAMETERS
# ============================================================================

# Frequency parameters
F_CENTER = {f_center}  # Hz
F_MIN = {f_min}  # Hz
F_MAX = {f_max}  # Hz
F_STEP = {f_step}  # Hz

# Substrate parameters
EPSILON_R = {epsilon_r}
H_SUBSTRATE = {h_substrate}  # m
L_SUBSTRATE = {l_substrate}  # m
W_SUBSTRATE = {w_substrate}  # m

# Dipole parameters
L_DIPOLE = {l_dipole}  # m (initial value for parameter sweep)
W_DIPOLE = {w_dipole}  # m

# Balun parameters
L_BALUN = {l_balun}  # m (quarter wavelength)
W_FEED_START = {w_feed_start}  # m
W_FEED_END = {w_feed_end}  # m

# Ground plane
L_GND = L_SUBSTRATE
W_GND = W_SUBSTRATE

# Model units
UNITS = "mm"

# ============================================================================
# LAUNCH AEDT AND CREATE PROJECT
# ============================================================================

print("Launching AEDT...")
try:
    # Try to connect to existing AEDT or launch new
    hfss = Hfss(
        projectname="Printed_Dipole_Antenna",
        designname="Dipole_Balun_Design",
        solution_type="Terminal Network",
        non_graphical=True,
        specified_version='2019.1'
    )
except Exception as e:
    print(f"AEDT connection error: {{e}}")
    print("Make sure Ansys Electronics Desktop is installed and licensed.")
    raise

print(f"Project: {{hfss.project_name}}")
print(f"Design: {{hfss.design_name}}")

# Set model units
hfss.modeler.model_units = UNITS

# ============================================================================
# CREATE SUBSTRATE
# ============================================================================

print("Creating FR4 substrate...")

# FR4 substrate box
substrate = hfss.modeler.create_box(
    position=[-L_SUBSTRATE/2, -W_SUBSTRATE/2, 0],
    dimensions_list=[L_SUBSTRATE, W_SUBSTRATE, H_SUBSTRATE],
    name="Substrate",
    material="FR4_epoxy"
)

print(f"  Substrate created: {{substrate.name}}")
print(f"  Dimensions: {{L_SUBSTRATE*1000:.1f}} x {{W_SUBSTRATE*1000:.1f}} x {{H_SUBSTRATE*1000:.2f}} mm")

# ============================================================================
# CREATE GROUND PLANE
# ============================================================================

print("Creating ground plane...")

ground = hfss.modeler.create_box(
    position=[-L_GND/2, -W_GND/2, H_SUBSTRATE],
    dimensions_list=[L_GND, W_GND, 0.035],  # 35 μm copper thickness
    name="Ground_Plane",
    material="copper"
)

print(f"  Ground plane created: {{ground.name}}")

# ============================================================================
# CREATE DIPOLE ARMS
# ============================================================================

print("Creating dipole arms...")

# Left dipole arm
left_arm = hfss.modeler.create_box(
    position=[-L_DIPOLE, -W_DIPOLE/2, H_SUBSTRATE],
    dimensions_list=[L_DIPOLE, W_DIPOLE, 0.035],
    name="Dipole_Left",
    material="copper"
)

# Right dipole arm
right_arm = hfss.modeler.create_box(
    position=[0, -W_DIPOLE/2, H_SUBSTRATE],
    dimensions_list=[L_DIPOLE, W_DIPOLE, 0.035],
    name="Dipole_Right",
    material="copper"
)

print(f"  Left arm: {{left_arm.name}}")
print(f"  Right arm: {{right_arm.name}}")

# ============================================================================
# CREATE MICROSTRIP BALUN (TAPERED FEED)
# ============================================================================

print("Creating microstrip balun...")

# Create tapered balun using multiple segments for approximation
num_segments = 10
balun_length = L_BALUN

# Create individual segments to approximate taper
for i in range(num_segments):
    x_pos = -balun_length + (i * balun_length / num_segments)
    width = W_FEED_START + (W_FEED_END - W_FEED_START) * (i / num_segments)
    next_width = W_FEED_START + (W_FEED_END - W_FEED_START) * ((i + 1) / num_segments)
    seg_length = balun_length / num_segments

    # Tapered segment (using average width)
    avg_width = (width + next_width) / 2

    segment = hfss.modeler.create_box(
        position=[x_pos, -avg_width/2, H_SUBSTRATE],
        dimensions_list=[seg_length + 0.001, avg_width, 0.035],
        name=f"Balun_Seg_{{i}}",
        material="copper"
    )

# Connect balun to dipole left arm
feed_point = hfss.modeler.create_box(
    position=[-balun_length - 1e-3, -W_FEED_START/2, H_SUBSTRATE],
    dimensions_list=[1e-3, W_FEED_START, 0.035],
    name="Feed_Point",
    material="copper"
)

print(f"  Balun segments: {{num_segments}}")
print(f"  Balun length: {{balun_length*1000:.2f}} mm")

# ============================================================================
# CREATE LUMPED PORT (FEED)
# ============================================================================

print("Creating lumped port excitation...")

# Create port at the feed point
hfss.lumped_port(
    name="Port1",
    faces=[hfss.modeler.get_faceid_from_position(feed_point.name, [0, 0, H_SUBSTRATE + 0.0175])],
    impedance=50,
    direction=[1, 0, 0]
)

print("  Lumped port 'Port1' created (50 ohm)")

# ============================================================================
# CREATE RADIATION BOUNDARY
# ============================================================================

print("Creating radiation boundary...")

# Create air box for radiation
air_box = hfss.modeler.create_box(
    position=[-L_SUBSTRATE, -L_SUBSTRATE, 0],
    dimensions_list=[L_SUBSTRATE * 3, L_SUBSTRATE * 3, L_SUBSTRATE * 2],
    name="Air_Box",
    material="air"
)

# Set up radiation boundary
hfss.create_open_region(
    name="Radiation_Boundary",
    boundary="Radiation",
    objects=["Air_Box"]
)

print("  Radiation boundary created")

# ============================================================================
# CREATE ANALYSIS SETUP
# ============================================================================

print("Creating frequency sweep setup...")

# Create setup with adaptive refinement
setup = hfss.create_setup(
    name="Setup1",
    setup_type="Hfss",
    Frequency=f_center,
    MaxDeltaZ=0.02,
    MaxPasses=15,
    MinimumPasses=3
)

# Add frequency sweep
hfss.create_linear_count_sweep(
    setupname="Setup1",
    sweepname="Freq_Sweep",
    StartValue=f_min,
    StopValue=f_max,
    Count=int((f_max - f_min) / f_step) + 1,
    SweepType="Linear",
    SaveFields=True
)

print(f"  Setup 'Setup1' created")
print(f"  Frequency sweep: {{F_MIN/1e9:.2f}} - {{F_MAX/1e9:.2f}} GHz, step {{F_STEP/1e6:.0f}} MHz")

# ============================================================================
# PARAMETER SWEEP FOR DIPOLE LENGTH OPTIMIZATION
# ============================================================================

print("Setting up parameter sweep for dipole length optimization...")

# Define parameter for sweep
hfss["L_dipole"] = f"{{L_DIPOLE}}mm"

# Create parameter sweep
hfss.optimizations.add_parametric_sweep(
    name="Length_Sweep",
    Variable="L_dipole",
    StartValue=f"{{L_DIPOLE*0.8}}mm",
    StopValue=f"{{L_DIPOLE*1.2}}mm",
    StepSize="1mm",
    VariationType="Linear",
    SaveFields=True
)

print("  Parameter sweep: 80% - 120% of initial length")

# ============================================================================
# SAVE AND ANALYZE
# ============================================================================

print("")
print("Saving project...")
hfss.save_project()

print("")
print("=" * 70)
print("Starting simulation...")
print("=" * 70)

# Analyze the setup
hfss.analyze_setup("Setup1", num_threads=4)

print("")
print("Simulation completed!")

# ============================================================================
# EXTRACT RESULTS
# ============================================================================

print("")
print("=" * 70)
print("Extracting S11 Results")
print("=" * 70)

# Get S11 data
s11_data = hfss.get_solution_data(
    "S11",
    "Setup1",
    "Freq_Sweep",
    "Port1",
    "Port1"
)

# Find resonance (minimum S11)
s11_mag = s11_data.data_real()
freqs = s11_data.sweeps["Freq_Sweep"]

# Find minimum S11
min_idx = np.argmin(s11_mag)
resonance_freq = freqs[min_idx]
min_s11 = s11_mag[min_idx]

print(f"  Resonance frequency: {{resonance_freq/1e9:.4f}} GHz")
print(f"  Minimum S11: {{min_s11:.2f}} dB")

# Calculate bandwidth (-10 dB criteria)
bandwidth_10db = []
for i, s11_val in enumerate(s11_mag):
    if s11_val < -10:
        bandwidth_10db.append(freqs[i])

if len(bandwidth_10db) >= 2:
    bw_low = min(bandwidth_10db)
    bw_high = max(bandwidth_10db)
    bandwidth = (bw_high - bw_low) / 1e9
    rel_bandwidth = (bandwidth / f_center) * 100
    print(f"  -10 dB Bandwidth: {{bw_low/1e9:.3f}} - {{bw_high/1e9:.3f}} GHz")
    print(f"  Relative bandwidth: {{rel_bandwidth:.2f}}%")
else:
    print("  S11 does not reach -10 dB threshold")

# ============================================================================
# FAR FIELD RADIATION PATTERN
# ============================================================================

print("")
print("=" * 70)
print("Computing Far Field Radiation Pattern")
print("=" * 70)

# Create far field sphere
hfss.create_open_region(
    name="Far_Field_Sphere",
    boundary="Radiation",
    objects=[]
)

# Compute far field at center frequency
ff_data = hfss.get_solution_data(
    "GainTotal",
    "Setup1",
    "Freq_Sweep",
    isInfiniteSphere=True,
    sphere_name="3D"
)

# Get gain at center frequency
gain_total = ff_data.data_real()
theta_vals = ff_data.sweeps.get("Theta", np.linspace(0, 180, 181))
phi_vals = ff_data.sweeps.get("Phi", [0])

# Find maximum gain
max_gain_idx = np.argmax(gain_total)
max_gain = gain_total[max_gain_idx]

print(f"  Maximum Gain: {{max_gain:.2f}} dBi")

# E-plane (xz-plane, phi=0) and H-plane (yz-plane, phi=90)
print("")
print("  Computing E-plane (xz) and H-plane (yz) patterns...")

# E-plane pattern (phi = 0)
e_plane_data = hfss.get_solution_data(
    "GainTotal",
    "Setup1",
    "Freq_Sweep",
    isInfiniteSphere=True,
    sphere_name="3D",
    Phi="0deg"
)

# H-plane pattern (phi = 90)
h_plane_data = hfss.get_solution_data(
    "GainTotal",
    "Setup1",
    "Freq_Sweep",
    isInfiniteSphere=True,
    sphere_name="3D",
    Phi="90deg"
)

print("")
print("=" * 70)
print("Design Summary")
print("=" * 70)
print(f"  Center Frequency: {{F_CENTER/1e9:.3f}} GHz (Target)")
print(f"  Resonance Frequency: {{resonance_freq/1e9:.4f}} GHz (Simulated)")
print(f"  Minimum S11: {{min_s11:.2f}} dB")
print(f"  Maximum Gain: {{max_gain:.2f}} dBi")
if len(bandwidth_10db) >= 2:
    print(f"  -10 dB Bandwidth: {{bandwidth*1000:.1f}} MHz ({{rel_bandwidth:.2f}}%)")

print("")
print("Simulation script generated successfully!")
print("Open the project in AEDT to view results and run optimizations.")

# Release AEDT
hfss.release_desktop()
'''.format(
    f_center=f_center,
    f_min=f_min,
    f_max=f_max,
    f_step=f_step,
    epsilon_r=epsilon_r,
    h_substrate=H_substrate,
    l_substrate=L_substrate,
    w_substrate=W_substrate,
    l_dipole=L_dipole_initial * 1e3,  # Convert to mm for script
    w_dipole=W_dipole * 1e3,
    l_balun=lambda_g / 4 * 1e3,
    w_feed_start=W_feed_start * 1e3,
    w_feed_end=W_feed_end * 1e3,
)

# Save the script
script_path = os.path.join(os.path.dirname(__file__), "printed_dipole_antenna.py")
with open(script_path, "w", encoding="utf-8") as f:
    f.write(hfss_script)

print(f"HFSS simulation script saved to: {script_path}")
print()

# ============================================================================
# STEP 4: Print Design Summary
# ============================================================================
print("=" * 70)
print("STEP 4: Design Summary")
print("=" * 70)

print("\n--- Antenna Design Parameters ---")
print(f"Center Frequency:     {f_center/1e9:.3f} GHz")
print(f"Free Space λ0:        {lambda_0*1e3:.2f} mm")
print(f"Guide λg (FR4):       {lambda_g*1e3:.2f} mm")
print(f"Initial Dipole Length: {L_dipole_initial*1e3:.1f} mm")
print(f"Optimal Dipole Length:  {L_dipole_optimal*1e3:.2f} mm (for reference)")
print(f"Balun Length (λg/4):   {L_balun*1e3:.2f} mm")

print("\n--- Substrate (FR4) ---")
print(f"Size:      {L_substrate*1e3:.1f} x {W_substrate*1e3:.1f} x {H_substrate*1e3:.2f} mm")
print(f"εr:        {epsilon_r}")
print(f"Thickness: {H_substrate*1e3:.2f} mm")

print("\n--- Simulation Settings ---")
print(f"Frequency Range: {f_min/1e9:.2f} - {f_max/1e9:.2f} GHz")
print(f"Sweep Step:       {f_step/1e6:.0f} MHz")
print(f"Number of Points: {int((f_max - f_min) / f_step) + 1}")

print("\n--- Expected Outputs ---")
print("1. S11 reflection coefficient vs frequency")
print("2. -10 dB bandwidth and relative bandwidth")
print("3. E-plane (xz-plane) radiation pattern")
print("4. H-plane (yz-plane) radiation pattern")
print("5. Antenna gain (dBi)")
print("6. Parameter sweep optimization for dipole length")

print("\n" + "=" * 70)
print("NEXT STEPS")
print("=" * 70)
print("""
1. Run the generated script in Python:
   python printed_dipole_antenna.py

2. The script will:
   - Launch Ansys AEDT (HFSS)
   - Create the antenna geometry
   - Set up the simulation
   - Run the analysis

3. After simulation completes, you can:
   - View S11 plot in AEDT
   - Export data to CSV for plotting
   - Run parameter sweep for optimization

4. If resonance is not at 2.217 GHz:
   - The script includes parameter sweep (80%-120% of initial length)
   - Find optimal length where S11 minimum aligns with 2.217 GHz
""")

# ============================================================================
# STEP 5: Generate Supporting Analysis Script
# ============================================================================
print("=" * 70)
print("STEP 5: Post-Processing Analysis Script")
print("=" * 70)

analysis_script = '''
"""
Post-Processing Analysis for Printed Dipole Antenna
Extracts and plots S11, radiation patterns, and calculates bandwidth
"""

import numpy as np
import matplotlib.pyplot as plt

def analyze_s11(frequencies, s11_db):
    """Analyze S11 data and find key parameters."""
    # Find resonance
    min_idx = np.argmin(s11_db)
    resonance_freq = frequencies[min_idx]
    min_s11 = s11_db[min_idx]

    # Find -10 dB bandwidth
    below_10db = np.where(s11_db < -10)[0]
    if len(below_10db) >= 2:
        bw_indices = below_10db[[0, -1]]
        bw_low = frequencies[bw_indices[0]]
        bw_high = frequencies[bw_indices[1]]
        bandwidth = bw_high - bw_low
        rel_bandwidth = (bandwidth / resonance_freq) * 100
    else:
        bw_low = bw_high = resonance_freq
        bandwidth = 0
        rel_bandwidth = 0

    return {
        "resonance_freq": resonance_freq,
        "min_s11": min_s11,
        "bw_low": bw_low,
        "bw_high": bw_high,
        "bandwidth": bandwidth,
        "relative_bandwidth": rel_bandwidth
    }

def plot_radiation_pattern(theta, gain_e, gain_h, title):
    """Plot E-plane and H-plane radiation patterns."""
    fig, ax = plt.subplots(subplot_kw='polar')
    ax.plot(np.radians(theta), gain_e, 'b-', label='E-plane (xz)', linewidth=2)
    ax.plot(np.radians(theta), gain_h, 'r--', label='H-plane (yz)', linewidth=2)
    ax.set_title(title, pad=20)
    ax.legend(loc='upper right')
    ax.set_theta_zero_location('N')
    ax.set_theta_direction(-1)
    plt.tight_layout()
    plt.show()

def plot_s11(frequencies, s11_db, resonance_freq, bandwidth_low, bandwidth_high):
    """Plot S11 reflection coefficient."""
    plt.figure(figsize=(10, 6))
    plt.plot(frequencies/1e9, s11_db, 'b-', linewidth=2)
    plt.axhline(y=-10, color='r', linestyle='--', label='-10 dB threshold')
    plt.axvline(x=resonance_freq/1e9, color='g', linestyle=':', label=f'Resonance: {resonance_freq/1e9:.3f} GHz')

    if bandwidth_low != bandwidth_high:
        plt.axvspan(bandwidth_low/1e9, bandwidth_high/1e9, alpha=0.2, color='green', label='-10 dB Bandwidth')

    plt.xlabel('Frequency (GHz)')
    plt.ylabel('S11 (dB)')
    plt.title('S11 Reflection Coefficient')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.show()

# Example usage with simulated data
if __name__ == "__main__":
    # Simulated S11 data (replace with actual AEDT data)
    freqs = np.linspace(1.5e9, 3.0e9, 151)
    s11_simulated = -10 * np.exp(-0.5 * ((freqs - 2.217e9) / 0.3e9)**2) - 2

    results = analyze_s11(freqs, s11_simulated)

    print("=" * 50)
    print("S11 Analysis Results")
    print("=" * 50)
    print(f"Resonance Frequency: {results['resonance_freq']/1e9:.4f} GHz")
    print(f"Minimum S11: {results['min_s11']:.2f} dB")
    print(f"-10 dB Bandwidth: {results['bw_low']/1e9:.3f} - {results['bw_high']/1e9:.3f} GHz")
    print(f"Bandwidth: {results['bandwidth']/1e6:.1f} MHz")
    print(f"Relative Bandwidth: {results['relative_bandwidth']:.2f}%")
'''

analysis_path = os.path.join(os.path.dirname(__file__), "dipole_analysis.py")
with open(analysis_path, "w", encoding="utf-8") as f:
    f.write(analysis_script)

print(f"Analysis script saved to: {analysis_path}")
print()
print("=" * 70)
print("DESIGN COMPLETE")
print("=" * 70)
print(f"""
Generated files:
1. printed_dipole_antenna.py - Main HFSS simulation script
2. dipole_analysis.py - Post-processing analysis script

To run the simulation:
1. Ensure Ansys Electronics Desktop (HFSS) is installed
2. Run: python printed_dipole_antenna.py
3. Wait for simulation to complete
4. Use dipole_analysis.py to plot results
""")
