"""
Printed Dipole Antenna with Microstrip Balun - HFSS Simulation
Generated by cli-anything-pyaedt

Antenna Specifications:
- Type: Printed Dipole with Microstrip Balun
- Center Frequency: 2.217 GHz
- Substrate: FR4 (εr = 4.4)
- Initial Dipole Length: 50.0 mm
"""

import numpy as np
import time

# ============================================================================
# PATCH PyAEDT for AEDT 2019.1 compatibility
# ============================================================================
import os
os.environ['ANSYSEM_ROOT193'] = r'C:\Program Files\AnsysEM\AnsysEM19.3\Win64'

# Patch Desktop.__init__ to avoid student_version AttributeError
try:
    from pyaedt import desktop
    _origDesktop_init = desktop.Desktop.__init__
    def _patched_Desktop_init(self, *args, **kwargs):
        _origDesktop_init(self, *args, **kwargs)
        if not hasattr(self, 'student_version'):
            self.student_version = False
    desktop.Desktop.__init__ = _patched_Desktop_init

    # Patch DesignSettings.__init__ to handle InsertDesign issue in AEDT 2019.1
    import pyaedt.application.Design as DesignModule
    _origDS_init = DesignModule.DesignSettings.__init__
    def _patched_DS_init(self, app):
        try:
            _origDS_init(self, app)
        except AttributeError:
            # AEDT 2019.1 workaround: GetChildObject may not be available yet
            self._app = app
            self.design_settings = None
            self.manipulate_inputs = None
    DesignModule.DesignSettings.__init__ = _patched_DS_init
except Exception:
    pass

from pyaedt import Hfss

# ============================================================================
# DESIGN PARAMETERS
# ============================================================================

# Frequency parameters
F_CENTER = 2217000000.0  # Hz
F_MIN = 1500000000.0  # Hz
F_MAX = 3000000000.0  # Hz
F_STEP = 10000000.0  # Hz

# Substrate parameters
EPSILON_R = 4.4
H_SUBSTRATE = 0.0016  # m
L_SUBSTRATE = 0.12  # m
W_SUBSTRATE = 0.06  # m

# Dipole parameters
L_DIPOLE = 50.0  # mm (initial value for parameter sweep)
W_DIPOLE = 3.0  # mm

# Balun parameters
L_BALUN = 16.12758100889026  # m (quarter wavelength)
W_FEED_START = 1.0  # m
W_FEED_END = 3.0  # m

# Ground plane
L_GND = L_SUBSTRATE
W_GND = W_SUBSTRATE

# Model units
UNITS = "mm"

# ============================================================================
# LAUNCH AEDT AND CREATE PROJECT
# ============================================================================

print("Launching AEDT...")
try:
    hfss = Hfss(
        projectname="Printed_Dipole_Antenna_v2",
        designname="Dipole_Balun_Design",
        solution_type="Terminal",
        non_graphical=True,
        new_desktop_session=True
    )
except Exception as e:
    print(f"AEDT connection error: {e}")
    raise

print(f"Project: {hfss.project_name}")
print(f"Design: {hfss.design_name}")

# Set model units
hfss.modeler.model_units = UNITS

# Get COM editor for direct geometry creation
oeditor = hfss.modeler.oeditor

# ============================================================================
# HELPER: Create box via COM interface
# ============================================================================
def create_box_com(name, x, y, z, dx, dy, dz, material):
    """Create a box using AEDT COM interface, then assign material."""
    # Create the box
    oeditor.CreateBox(
        [
            "NAME:BoxParameters",
            "XPosition:=", str(x),
            "YPosition:=", str(y),
            "ZPosition:=", str(z),
            "XSizing:=", str(dx),
            "YSizing:=", str(dy),
            "ZSizing:=", str(dz)
        ],
        [
            "NAME:Attributes",
            "Name:=", name,
            "Flags:=", "",
            "Color:=", "(143 175 131)",
            "Transparency:=", 0,
            "PartCoordinateSystem:=", "Global",
            "UDMList:=", [],
            "MaterialValue:=", '"' + material + '"',
            "SurfaceMaterialValue:=", '""',
            "SolveInside:=", "true" if material.lower() not in ["copper", "pec", "aluminum"] else "false",
            "IsMaterialEditable:=", "true",
            "UseMaterialAppearance:=", "false",
            "IsLightweight:=", "false"
        ]
    )

# ============================================================================
# CREATE SUBSTRATE
# ============================================================================

print("Creating FR4 substrate...")
x_sub = -L_SUBSTRATE * 1000 / 2  # convert to mm
y_sub = -W_SUBSTRATE * 1000 / 2
z_sub = 0
dx_sub = L_SUBSTRATE * 1000
dy_sub = W_SUBSTRATE * 1000
dz_sub = H_SUBSTRATE * 1000

create_box_com("Substrate", x_sub, y_sub, z_sub, dx_sub, dy_sub, dz_sub, "FR4_epoxy")
print(f"  Substrate created: 120 x 60 x 1.6 mm")

# ============================================================================
# CREATE GROUND PLANE
# ============================================================================

print("Creating ground plane...")
x_gnd = -L_GND * 1000 / 2
y_gnd = -W_GND * 1000 / 2
z_gnd = H_SUBSTRATE * 1000
create_box_com("Ground_Plane", x_gnd, y_gnd, z_gnd, L_GND*1000, W_GND*1000, 0.035, "copper")
print(f"  Ground plane created")

# ============================================================================
# CREATE DIPOLE ARMS
# ============================================================================

print("Creating dipole arms...")

# Left dipole arm (extends from -L_DIPOLE to 0)
x_left = -L_DIPOLE - L_DIPOLE  # starts at -50mm from origin, extends left
y_left = -W_DIPOLE / 2
z_left = H_SUBSTRATE * 1000
create_box_com("Dipole_Left", x_left, y_left, z_left, L_DIPOLE, W_DIPOLE, 0.035, "copper")

# Right dipole arm (extends from 0 to +L_DIPOLE)
x_right = 0
y_right = -W_DIPOLE / 2
create_box_com("Dipole_Right", x_right, y_right, z_left, L_DIPOLE, W_DIPOLE, 0.035, "copper")

print(f"  Left arm: {L_DIPOLE} x {W_DIPOLE} x 0.035 mm at x={x_left}")
print(f"  Right arm: {L_DIPOLE} x {W_DIPOLE} x 0.035 mm at x={x_right}")

# ============================================================================
# CREATE MICROSTRIP BALUN (TAPERED FEED)
# ============================================================================

print("Creating microstrip balun...")

num_segments = 10
balun_length_mm = L_BALUN * 1000  # convert to mm

for i in range(num_segments):
    x_pos = -balun_length_mm + (i * balun_length_mm / num_segments)
    width = W_FEED_START * 1000 + (W_FEED_END - W_FEED_START) * 1000 * (i / num_segments)
    next_width = W_FEED_START * 1000 + (W_FEED_END - W_FEED_START) * 1000 * ((i + 1) / num_segments)
    seg_length = balun_length_mm / num_segments
    avg_width = (width + next_width) / 2

    create_box_com(
        f"Balun_Seg_{i}",
        x_pos, -avg_width/2, z_left,
        seg_length + 0.001, avg_width, 0.035,
        "copper"
    )

# Feed point (connection to balun)
feed_x = -balun_length_mm - 1
create_box_com("Feed_Point", feed_x, -W_FEED_START*1000/2, z_left, 1, W_FEED_START*1000, 0.035, "copper")

print(f"  Balun segments: {num_segments}")
print(f"  Balun length: {balun_length_mm:.2f} mm")

# ============================================================================
# CREATE LUMPED PORT (FEED)
# ============================================================================

print("Creating lumped port excitation...")

# Get the face of Feed_Point closest to the balun (right side face)
# We need to find the face at x = feed_x + 1 (the right face of Feed_Point)
hfss.lumped_port(
    name="Port1",
    faces=[hfss.modeler.get_faceid_from_position("Feed_Point", [feed_x + 0.5, 0, z_left + 0.0175])],
    impedance=50,
    direction=[1, 0, 0]
)

print("  Lumped port 'Port1' created (50 ohm)")

# ============================================================================
# CREATE RADIATION BOUNDARY
# ============================================================================

print("Creating radiation boundary...")

# Create air box
air_size = L_SUBSTRATE * 1000
create_box_com(
    "Air_Box",
    -air_size, -air_size, 0,
    air_size * 3, air_size * 3, air_size * 2,
    "air"
)

# Set radiation boundary on air box faces
hfss.create_open_region(
    name="Radiation_Boundary",
    boundary="Radiation",
    objects=["Air_Box"]
)

print("  Radiation boundary created")

# ============================================================================
# CREATE ANALYSIS SETUP
# ============================================================================

print("Creating frequency sweep setup...")

setup = hfss.create_setup(
    name="Setup1",
    setup_type="Hfss",
    Frequency=F_CENTER,
    MaxDeltaZ=0.02,
    MaxPasses=15,
    MinimumPasses=3
)

hfss.create_linear_count_sweep(
    setupname="Setup1",
    sweepname="Freq_Sweep",
    StartValue=F_MIN,
    StopValue=F_MAX,
    Count=int((F_MAX - F_MIN) / F_STEP) + 1,
    SweepType="Linear",
    SaveFields=True
)

print(f"  Setup 'Setup1' created")
print(f"  Frequency sweep: {F_MIN/1e9:.2f} - {F_MAX/1e9:.2f} GHz, step {F_STEP/1e6:.0f} MHz")

# ============================================================================
# PARAMETER SWEEP FOR DIPOLE LENGTH OPTIMIZATION
# ============================================================================

print("Setting up parameter sweep for dipole length optimization...")

hfss["L_dipole"] = f"{L_DIPOLE}"

hfss.optimizations.add_parametric_sweep(
    name="Length_Sweep",
    Variable="L_dipole",
    StartValue=f"{L_DIPOLE*0.8}",
    StopValue=f"{L_DIPOLE*1.2}",
    StepSize="1",
    VariationType="Linear",
    SaveFields=True
)

print("  Parameter sweep: 80% - 120% of initial length")

# ============================================================================
# SAVE AND ANALYZE
# ============================================================================

print("")
print("Saving project...")
hfss.save_project()

print("")
print("=" * 70)
print("Starting simulation...")
print("=" * 70)

hfss.analyze_setup("Setup1", num_threads=4)

print("")
print("Simulation completed!")

# ============================================================================
# EXTRACT RESULTS
# ============================================================================

print("")
print("=" * 70)
print("Extracting S11 Results")
print("=" * 70)

s11_data = hfss.get_solution_data(
    "S11",
    "Setup1",
    "Freq_Sweep",
    "Port1",
    "Port1"
)

s11_mag = s11_data.data_real()
freqs = s11_data.sweeps["Freq_Sweep"]

min_idx = np.argmin(s11_mag)
resonance_freq = freqs[min_idx]
min_s11 = s11_mag[min_idx]

print(f"  Resonance frequency: {resonance_freq/1e9:.4f} GHz")
print(f"  Minimum S11: {min_s11:.2f} dB")

# Calculate bandwidth (-10 dB criteria)
bandwidth_10db = []
for i, s11_val in enumerate(s11_mag):
    if s11_val < -10:
        bandwidth_10db.append(freqs[i])

if len(bandwidth_10db) >= 2:
    bw_low = min(bandwidth_10db)
    bw_high = max(bandwidth_10db)
    bandwidth = (bw_high - bw_low) / 1e9
    rel_bandwidth = (bandwidth / F_CENTER) * 100
    print(f"  -10 dB Bandwidth: {bw_low/1e9:.3f} - {bw_high/1e9:.3f} GHz")
    print(f"  Relative bandwidth: {rel_bandwidth:.2f}%")
else:
    print("  S11 does not reach -10 dB threshold")

# ============================================================================
# FAR FIELD RADIATION PATTERN
# ============================================================================

print("")
print("=" * 70)
print("Computing Far Field Radiation Pattern")
print("=" * 70)

hfss.create_open_region(
    name="Far_Field_Sphere",
    boundary="Radiation",
    objects=[]
)

ff_data = hfss.get_solution_data(
    "GainTotal",
    "Setup1",
    "Freq_Sweep",
    isInfiniteSphere=True,
    sphere_name="3D"
)

gain_total = ff_data.data_real()
theta_vals = ff_data.sweeps.get("Theta", np.linspace(0, 180, 181))
phi_vals = ff_data.sweeps.get("Phi", [0])

max_gain_idx = np.argmax(gain_total)
max_gain = gain_total[max_gain_idx]

print(f"  Maximum Gain: {max_gain:.2f} dBi")

# E-plane (xz-plane, phi=0) and H-plane (yz-plane, phi=90)
print("")
print("  Computing E-plane (xz) and H-plane (yz) patterns...")

e_plane_data = hfss.get_solution_data(
    "GainTotal",
    "Setup1",
    "Freq_Sweep",
    isInfiniteSphere=True,
    sphere_name="3D",
    Phi="0deg"
)

h_plane_data = hfss.get_solution_data(
    "GainTotal",
    "Setup1",
    "Freq_Sweep",
    isInfiniteSphere=True,
    sphere_name="3D",
    Phi="90deg"
)

print("")
print("=" * 70)
print("Design Summary")
print("=" * 70)
print(f"  Center Frequency: {F_CENTER/1e9:.3f} GHz (Target)")
print(f"  Resonance Frequency: {resonance_freq/1e9:.4f} GHz (Simulated)")
print(f"  Minimum S11: {min_s11:.2f} dB")
print(f"  Maximum Gain: {max_gain:.2f} dBi")
if len(bandwidth_10db) >= 2:
    print(f"  -10 dB Bandwidth: {bandwidth*1000:.1f} MHz ({rel_bandwidth:.2f}%)")

print("")
print("Simulation completed successfully!")
print("Open the project in AEDT to view results and run optimizations.")

hfss.release_desktop()
